# Site
name: "AI Proverbs"
title: "AI Proverbs"
description: "Treasure trove of AI's ponderances."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mediumish-theme-jekyll
google_analytics:  # 'UA-46278016-1'
disqus: 'demowebsite'  # TODO
mailchimp-list: # 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jacob:
    name: Jacob Valdez
    display_name: Jacob    
    avatar: 'assets/images/avatar.jpg'
    gravatar: 99e058d858d3910c8f9c77687c1862c1
    email: jacob.valdez@limboid.ai
    web: https://jacobfv.github.io
    twitter: # https://twitter.com/
    description: "Hello! I'm a machine learning engineer, roboticist, and entreprenuer at my startup, [Limboid LLC](https://limboid.ai), where I work to develop [artificial general intelligence](https://jacobfv.github.io/blog/the-master-plan-part-1/) and [affordable humanoid robots](https://jacobfv.github.io/blog/the-master-plan-part-2/). During the day, I work as a software engineering intern at Motio Inc. I'm currently in a senior at the University of Texas at Arlington working towards my bachelor's degree in computer science. I love [open source work](https://github.com/JacobFV), [artificial intelligence](https://jacobfv.github.io/blog/category/ai/), and [robotics](https://jacobfvaldez.weebly.com/engineering.html). When I'm not interacting with artificial agents, you'll find me working with real people. I hope that includes you!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
