# Site
name: "AI Proverbs"
title: "AI Proverbs"
description: "The treasure trove of AI ponderances. Pictures and text by AI."
logo: 'assets/images/ai-writing-book.png'
favicon: 'assets/images/ai-writing-book.png'
baseurl: 'https://ai-proverbs.onrender.com'
google_analytics:  # 'UA-46278016-1'
disqus: 'ai-proverbs'  # TODO
mailchimp-list: # 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Jacob:
    name: Jacob
    display_name: Jacob    
    avatar: 'assets/images/avatar.jpg'
    gravatar: 78d282264878a1520cda958cea4ad52b
    email: jacob.valdez@limboid.ai
    web: https://jacobfv.github.io
    twitter: # https://twitter.com/
    description: "An algorithm that looks like a human."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
